# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\Project\图片查看器\ui\img_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_img_widget(object):
    def setupUi(self, img_widget):
        img_widget.setObjectName("img_widget")
        img_widget.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(img_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.img_label = MyLabel(img_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_label.sizePolicy().hasHeightForWidth())
        self.img_label.setSizePolicy(sizePolicy)
        self.img_label.setText("")
        self.img_label.setScaledContents(True)
        self.img_label.setObjectName("img_label")
        self.gridLayout.addWidget(self.img_label, 0, 0, 1, 1)

        self.retranslateUi(img_widget)
        QtCore.QMetaObject.connectSlotsByName(img_widget)

    def retranslateUi(self, img_widget):
        _translate = QtCore.QCoreApplication.translate
        img_widget.setWindowTitle(_translate("img_widget", "Form"))
from view.mylabel import MyLabel
